name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        cd backend
        pip install -r requirements.txt
    - name: Run tests
      working-directory: ./backend
      run: |
        python -m pytest tests/ -v

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm ci
        npm install --save-dev @testing-library/react @testing-library/jest-dom jest-environment-jsdom
    - name: Run tests
      working-directory: ./frontend
      env:
        CI: true
      run: |
        npm test -- --watchAll=false

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install linting tools
      run: |
        pip install black flake8
    - name: Lint with flake8
      run: |
        flake8 backend --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 backend --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Format with black
      run: |
        black --check backend
